name: Development branches

on:
  push:
    branches:
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup JDK and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.5
          distribution: 'zulu'
          cache: maven
          server-id: ossrh
          server-username: OSS_CENTRAL_USERNAME # env variable for Maven Central
          server-password: OSS_CENTRAL_PASSWORD # env variable for Maven Central

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4 -ntp

#      # Publish snapshot
#      - name: Deploy a new snapshot to Maven Central
#        run: ./mvnw clean deploy -B -DskipTests -DskipExamples -Prelease -Dgpg.keyname=${{ secrets.GPG_KEYNAME }} -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
#        env:
#          OSS_CENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          OSS_CENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
