name: Development branches

permissions:
  contents: read

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'
  pull_request:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip tests?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup JDK and Maven
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .java-version
          cache: maven

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4 -ntp
