name: Development branches

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and tests on JDK 11
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup the cache
      - name: Cache .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Setup JDK and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSS_CENTRAL_USERNAME # env variable for Maven Central
          server-password: OSS_CENTRAL_PASSWORD # env variable for Maven Central
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          gpg-private-key: ${{ secrets.GPG_SECRET_KEYS }}

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4

      # Publish snapshot (simulate for now)
      - name: Deploy a new snapshot to Maven Central
        run: ./mvnw clean deploy -B -DskipTests -DskipExamples -Prelease -DdryRun
        env:
          OSS_CENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSS_CENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          # MAVEN_GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

